apiVersion: skaffold/v1
kind: Config
metadata:
  name: kafka
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/kafka/*

---
apiVersion: skaffold/v1
kind: Config
metadata:
  name: create-topics
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/create-topics/*
build:
  local:
    push: false
  artifacts:
    - image: khalilcoder/create-topics
      context: topics
      docker:
        dockerfile: Dockerfile

---
apiVersion: skaffold/v1
kind: Config
metadata:
  name: microservices
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/microservices/*
      - ./infra/k8s/k8s-ingress-dev/*
build:
  local:
    push: false
  artifacts:
    - image: khalilcoder/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khalilcoder/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: khalilcoder/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khalilcoder/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khalilcoder/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: khalilcoder/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
