apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: khalilcoder/orders
          env:
            - name: KAFKA_CLIENT_ID
              value: "ticketing"
            - name: BROKER_URL
              value: "kafka-broker-1-srv:9092"
            - name: MONGO_URI
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_WHOOK
              valueFrom:
                secretKeyRef:
                  name: stripe-whook
                  key: STRIPE_WHOOK
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
